-- CSE
SELECT H.C_NAME, O.O_ORDERKEY, O.O_TOTALPRICE 
FROM (
  SELECT CUSTOMER.C_CUSTKEY, CUSTOMER.C_NAME, CUSTOMER.C_ACCTBAL 
  FROM CUSTOMER 
  WHERE CUSTOMER.C_ACCTBAL > 1000
) H
JOIN (
  SELECT CUSTOMER.C_CUSTKEY, CUSTOMER.C_NAME, CUSTOMER.C_ACCTBAL 
  FROM CUSTOMER 
  WHERE CUSTOMER.C_ACCTBAL > 1000
) I ON H.CUSTOMER.C_NATIONKEY = I.CUSTOMER.C_NATIONKEY
JOIN ORDERS O ON H.CUSTOMER.C_CUSTKEY = O.O_CUSTKEY 
WHERE O.O_TOTALPRICE > 50000 AND O.O_ORDERSTATUS = 'O' OR O.O_SHIPPRIORITY = 0

-- Pred Push
SELECT L.L_ORDERKEY, L.L_PARTKEY
FROM LINEITEM L
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE L.L_SHIPDATE >= '1994-01-01' AND O.O_ORDERSTATUS = 'F'


-- Join
SELECT P.P_NAME, P.P_BRAND
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
WHERE P.P_SIZE >= 25

-- Join
SELECT S.S_NAME, N.N_NAME, L.L_EXTENDEDPRICE, O.O_ORDERDATE
FROM SUPPLIER S
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE L.L_DISCOUNT > 0.05

-- Join
SELECT 
    P.P_NAME,
    PS.PS_SUPPLYCOST,
    S.S_NAME,
    N.N_NAME,
    R.R_NAME
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
WHERE PS.PS_SUPPLYCOST < 300
  AND R.R_NAME = 'EUROPE';

-- Join
SELECT P.P_NAME, S.S_NAME, N.N_NAME, PS.PS_SUPPLYCOST
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
WHERE P.P_TYPE = 'COPPER'
  AND PS.PS_SUPPLYCOST < 500;

-- Subsequence
SELECT H.S_NAME, I.S_PHONE, N.N_NAME
FROM (
  SELECT SUPPLIER.S_SUPPKEY, SUPPLIER.S_NAME, SUPPLIER.S_NATIONKEY
  FROM SUPPLIER
  WHERE SUPPLIER.S_ACCTBAL > 5000
) H
JOIN (
  SELECT SUPPLIER.S_SUPPKEY, SUPPLIER.S_PHONE, SUPPLIER.S_NATIONKEY
  FROM SUPPLIER
  WHERE SUPPLIER.S_ACCTBAL > 5000
) I ON H.SUPPLIER.S_NATIONKEY = I.SUPPLIER.S_NATIONKEY
JOIN NATION N ON H.SUPPLIER.S_NATIONKEY = N.N_NATIONKEY
WHERE N.N_NAME = 'UNITED STATES'


-- Subquery with multiple joins
SELECT o.orderkey, l.quantity, s.suppkey, c.custkey
FROM orders o 
JOIN customer c ON o.custkey = c.custkey
JOIN lineitem l ON o.orderkey = l.orderkey
JOIN supplier s ON s.suppkey = l.suppkey
JOIN (SELECT n.nationkey, n.name FROM nation n) tmp1 ON tmp1.nationkey = c.nationkey
JOIN (SELECT n.nationkey, n.name FROM nation n) tmp2 ON tmp2.nationkey = s.nationkey

-- Subquery with multiple joins 2
SELECT ps.partkey, ps.supplykey
FROM partsupp ps 
JOIN supplier s ON ps.supplykey = s.supplykey
JOIN lineitem l ON ps.supplykey = l.supplykey
JOIN (SELECT p.name, p.brand FROM part p) tmp1 ON tmp1.partkey = ps.partkey
JOIN (SELECT p.name, p.brand FROM part p) tmp2 ON tmp2.partkey = l.partkey
WHERE ps.availqty > 10 AND s.acctbal > 1000

-- Project before Select
  SELECT p.partkey, p.suppkey
  FROM partsupp p
  JOIN supplier s ON p.suppkey = s.suppkey
  WHERE p.availqty > 10 OR p.supplycost < 500 AND s.acctbal > 1000