SELECT H.C_NAME, O.O_ORDERKEY, O.O_TOTALPRICE 
FROM (
  SELECT CUSTOMER.C_CUSTKEY, CUSTOMER.C_NAME, CUSTOMER.C_ACCTBAL 
  FROM CUSTOMER 
  WHERE CUSTOMER.C_ACCTBAL > 1000
) H
JOIN ORDERS O ON H.CUSTOMER.C_CUSTKEY = O.O_CUSTKEY 
WHERE O.O_TOTALPRICE > 50000 AND O.O_ORDERSTATUS = 'O' OR O.O_SHIPPRIORITY = 0

