-- CSE
SELECT H.C_NAME, O.O_ORDERKEY, O.O_TOTALPRICE 
FROM (
  SELECT CUSTOMER.C_CUSTKEY, CUSTOMER.C_NAME, CUSTOMER.C_ACCTBAL 
  FROM CUSTOMER 
  WHERE CUSTOMER.C_ACCTBAL > 1000
) H
JOIN (
  SELECT CUSTOMER.C_CUSTKEY, CUSTOMER.C_NAME, CUSTOMER.C_ACCTBAL 
  FROM CUSTOMER 
  WHERE CUSTOMER.C_ACCTBAL > 1000
) I ON H.CUSTOMER.C_NATIONKEY = I.CUSTOMER.C_NATIONKEY
JOIN ORDERS O ON H.CUSTOMER.C_CUSTKEY = O.O_CUSTKEY 
WHERE O.O_TOTALPRICE > 50000 AND O.O_ORDERSTATUS = 'O' OR O.O_SHIPPRIORITY = 0

-- Pred Push
SELECT L.L_ORDERKEY, L.L_PARTKEY
FROM LINEITEM L
JOIN ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
WHERE L.L_SHIPDATE >= '1994-01-01' AND O.O_ORDERSTATUS = 'F'


-- Join
SELECT P.P_NAME, P.P_BRAND
FROM PART P
JOIN PARTSUPP PS ON P.P_PARTKEY = PS.PS_PARTKEY
JOIN SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
WHERE P.P_SIZE >= 25
